import pulumi

cfg = pulumi.Config()
dbSourceUserName = cfg.require('dbSourceUserName')
dbSourcePSW = pulumi.Output.all(cfg.get_secret('dbSourcePSW'))\
    .apply(lambda args: args[0]) 
dbDWHName = cfg.require('dbDWHName')
dbSourceName = cfg.require('dbSourceName')
resourceGroupName = cfg.require('resourceGroupName')
serverName= cfg.require('serverName')
storageAccountDestinationName= cfg.require('storageAccountDestinationName')
storageAccountSourceName= cfg.require('storageAccountSourceName')
blobContainerName = cfg.require('blobContainerName')
factoryName = cfg.require('factoryName')

print("Admin User Name: "+dbSourceUserName)
print("Admin PSW: "+ dbSourcePSW)
print("DB for Datawarehouse: "+dbDWHName)
print("DB Source: "+dbSourceName)
print("Resource Group Name: "+resourceGroupName)
print("Server Name: "+serverName)
print("Storage Destination Name: "+storageAccountDestinationName)
print("Storage Source Name: "+storageAccountSourceName)
print("Blob Container Name: "+blobContainerName)
print("Factory Name: "+factoryName)